name: cstock tests
on:
  pull_request:
    branches:
    - malawi-dev
#  schedule:
#    - cron: '0 0 * * *'
jobs:
  tests:
    runs-on: ubuntu-18.04
    timeout-minutes: 60
    strategy:
      max-parallel: 4
      matrix:
        db: [mysql]
        python-version: [ 2.7 ]
        include:
          - db: mysql
            db_port: 3306
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: hunter2
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        env:
          DB_USER: ${{ matrix.db_user }}
          DB_PASSWORD: ${{ matrix.db_password }}
          GITHUB_TESTS: yes
        run: |
          python manage.py test logistics_project.apps.malawi.tests.boot
